### ISSUE TITLE
How to define the dataset?

### ISSUE THREAD

**Issue by scutfrank** [mateoespinosa/cem#1]
Please help to set the example if I want to train in celebA dataset, thanks!

**Comment by mateoespinosa** [comment]
Thank you so much for raising this issue and apologies for the delay. I have added a standalone loader for the CelebA dataset that we used (see [this change](https://github.com/mateoespinosa/cem/commit/0797f0d899f2ff6de74217f1829e12e2f5a97ad6#diff-3bd6423deae105c8af58e78067b7c88cb416cac2cf80aa1e728933290990fe97R109)) and an example of how to train a model in this dataset can be seen by running:
```bash
python experiments/intervention_experiments.py celeba
```
after the `cem` package has been installed.

Please make sure to set the environment variable ` DATASET_DIR` to the location of the `CelebA` data before running the command above. If you have any further questions, feel free to open up another ticket and/or comment in this ticket.
