### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'task_class_weights'

### ISSUE THREAD

**Issue by BobBranson** [mateoespinosa/cem#2]
When executing the command "python experiments/run_experiments.py dot -o dot_results/"，there is a error. 

Error Info: 
  File "D:\0develop\miniconda3\envs\CEM_NeurIPS\lib\site-packages\cem-1.0.0-py3.8.egg\cem\train\training.py", line 151, in construct_sequential_models
TypeError: __init__() got an unexpected keyword argument 'task_class_weights'

This is after I successfully executed "$ python setup.py install" because cmd showed "Finished processing dependencies for cem==1.0.0". 

SO, is there a code problem with the packed "cem-1.0.0-py3.8.egg" file that "$ python setup.py install" creates  and how to solve this problem?

**Comment by mateoespinosa** [comment]
Hi @BobBranson! Thank you so much for raising this issue and apologies for the inconvenience. I recently merged a new update for this repository in a new PR (see #4) that might've fixed this issue. Could you please try out the new instructions in the README to run the experiment and re-raise an issue (with details on your own setup and software versions) if you are still having trouble running the experiment script?

Thank you so much for helping us make this repository more usable!
