### ISSUE TITLE
Computing CAS for non-concept models

### ISSUE THREAD

**Issue by FlorentF9** [mateoespinosa/cem#7]
Thanks for the great paper and repo!

I have a question on how to compute the concept alignment score (CAS) for non-concept-based models.
In your paper, you report CAS for "No concepts" models, but it is not clear on which embeddings the score should be computed.
Should it be computed on the latent code **h** ?

**Comment by pietrobarbiero** [comment]
Hi @FlorentF9 ! Yes, we computed the CAS score on the latent code **h** as "No concepts" models do not have an explicit "concept layer".

**Comment by FlorentF9** [comment]
Thanks for confirming!
